version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: rag_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
    - qdrant
    restart: on-failure
    networks:
      - rag_network

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: rag_frontend
    ports:
      - "8501:8501"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - rag_network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: rag_qdrant
    ports:
      - "6333:6333" 
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - rag_network

networks:
  rag_network:
    driver: bridge

volumes:
  qdrant_storage:
